apiVersion: v1
kind: Service
metadata:
  name: {{ include "gentian-portal.fullname" . }}-api
  labels:
    {{- include "gentian-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: {{ include "gentian-portal.name" . }}-api
  ports:
    - port: 8000
      targetPort: http
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gentian-portal.fullname" . }}-web
  labels:
    {{- include "gentian-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  selector:
    app.kubernetes.io/name: {{ include "gentian-portal.name" . }}-web
  ports:
    - port: {{ .Values.web.port }}
      targetPort: http
      name: http
